/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.RRHormonas;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ale
 */
public class Interfaz extends javax.swing.JFrame {

    int consumidos = 0;
    int intestino = 0;
    int hormonas_Segregadas = 0;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        alimentos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alimentosConsumidos = new javax.swing.JTextArea();
        alimentos1 = new javax.swing.JLabel();
        alimentos3 = new javax.swing.JLabel();
        alimentos2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        capacidadIn = new javax.swing.JTextArea();
        alimentos4 = new javax.swing.JLabel();
        alimentos5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        hormonasSegre = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        consola = new javax.swing.JScrollPane();
        consolaa = new javax.swing.JTextArea();
        comida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Comer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ezgif.com-resize.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, 260));

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Vaciar Intestino");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 120, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        alimentos.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        alimentos.setText("consumidos");
        getContentPane().add(alimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        alimentosConsumidos.setColumns(5);
        alimentosConsumidos.setRows(2);
        alimentosConsumidos.setTabSize(2);
        jScrollPane2.setViewportView(alimentosConsumidos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        alimentos1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        alimentos1.setText("Alimentos");
        getContentPane().add(alimentos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        alimentos3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        alimentos3.setText("intestino");
        getContentPane().add(alimentos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        alimentos2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        alimentos2.setText("Capacidad");
        getContentPane().add(alimentos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        capacidadIn.setColumns(5);
        capacidadIn.setRows(2);
        capacidadIn.setTabSize(2);
        jScrollPane3.setViewportView(capacidadIn);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        alimentos4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        alimentos4.setText("Segregadas");
        getContentPane().add(alimentos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        alimentos5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        alimentos5.setText("Hormonas");
        getContentPane().add(alimentos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        hormonasSegre.setColumns(5);
        hormonasSegre.setRows(2);
        hormonasSegre.setTabSize(2);
        jScrollPane4.setViewportView(hormonasSegre);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel3.setText("Sistema Digestivo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel4.setText("Presione Comer para poner a trabajar el sistema digestivo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        consolaa.setColumns(20);
        consolaa.setRows(5);
        consolaa.setText("Empecemos");
        consola.setViewportView(consolaa);

        getContentPane().add(consola, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 250, 220));
        getContentPane().add(comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 110, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RRHormonas lista_hormonas = new RRHormonas();
        List<Integer> lista = lista_hormonas.RoundRobin();
        //Limpiar el cuadro de trabajo
        consolaa.setText("");
        //Actualizar el contador de la capacidad del intestino
        if (intestino < 3) {
            intestino++;
            capacidadIn.setText(Integer.toString(intestino) + "/3");
            //Seleccionaremos aleatoriamente los alimentos que se consumiran
            
            consumidos++;
            //Actualizar el contador de alimentos consumidos
            alimentosConsumidos.setText("   " + Integer.toString(consumidos));
            int dados = (int) (Math.random() * 100) + 20;
            if (dados % 2 == 0) {
                consolaa.append("Se comió pizza");
            } else {
                consolaa.append("Se comió enchiladas");
            }
            hormonas_Segregadas+=3;
            hormonasSegre.setText(Integer.toString(hormonas_Segregadas));
            
            //consolaa.append("Empezamos a comer una "+alimento);
            for (int cont = 0; cont < lista.size(); cont++) {

                System.out.println(lista.get(cont));
                if (null != lista.get(cont)) {
                    switch (lista.get(cont)) {
                        case 0:
                            consolaa.append("\n\n==Insulina trabajando ==");
                            break;
                        case 1:
                            consolaa.append("\n\n==Liptina trabajando==");
                            break;
                        case 2:
                            consolaa.append("\n\n==Grelina trabajando==");
                            break;
                        default:
                            break;
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "¡Debemos vaciar el intestino!", "Error al intentar comer", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        intestino = 0;
        capacidadIn.setText("0/3");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alimentos;
    private javax.swing.JLabel alimentos1;
    private javax.swing.JLabel alimentos2;
    private javax.swing.JLabel alimentos3;
    private javax.swing.JLabel alimentos4;
    private javax.swing.JLabel alimentos5;
    private javax.swing.JTextArea alimentosConsumidos;
    private javax.swing.JTextArea capacidadIn;
    private javax.swing.JLabel comida;
    private javax.swing.JScrollPane consola;
    private javax.swing.JTextArea consolaa;
    private javax.swing.JTextArea hormonasSegre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
